### ISSUE TITLE
PriceDialog bug

### ISSUE THREAD

**Issue by janissuonpera** [janissuonpera/tiko_ht#5]
Rivil 62 PriceDialog.java heittää error, kun asetin työkohteeseen 10h suunnittelutyön. Ei parsee sitä hintaa oikein siitä vaan nappaa mukaan jotain stringiäkin. En ehdi vielä katsomaan ajan kanssa sitä kuntoon. Korjatkaa jos ehditte.

**Comment by janissuonpera** [comment]
Saattaa olla joku encoding error kans? Jos teillä toimii fine nii ilmottakaa.

**Comment by OscarGTH** [comment]
Joo, bugi johtuu siitä, kun yrität splittaa tota stringii sen € kohdalta, mutta enkoodaus muutosten takia DBHandler on palauttanut €☐. Eli vaihdan vaikka tuon €-merkin kirjainjonoksi "euroa", niin enkoodaus ei pitäis muuttaa sitä mikskään.
