### ISSUE TITLE
Index out of bounds exception

### ISSUE THREAD

**Issue by janissuonpera** [janissuonpera/tiko_ht#6]
Muokkaa työkohdetta --> Kustannukset aiheuttaa indexOutOfBoundsExceptionin rivillä 86 PriceDialog-luokassa.

**Comment by OscarGTH** [comment]
Oliko sulla yhtään tarviketta sun listassa? Sain ite kaatumaa sillee et en laittanu mitää tavaraa sinne, mut korjasin ton.
