### ISSUE TITLE
Suoritustarvikkeet eivät tallennu virhetilanteessa oikein

### ISSUE THREAD

**Issue by janissuonpera** [janissuonpera/tiko_ht#7]
Jos käyttäjä vahingossa työsuorituksessa laittaa saman tarvikkeen 2 kertaa listalle, tulee sql errori, koska se tarvike on jo samalta työsuoritukselta. Pitäisi estää saman tarvikkeen lisääminen monta kertaa.

**Comment by OscarGTH** [comment]
Korjattu. Lista tarkistetaan nyt duplikaattien varalta ja jos sellainen löytyy, niin lisätään vain kappalemäärä.
